server:
  port: 8080
  servlet:
    context-path: /Travel
  error:
    whitelabel:
      enabled: true
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traveldb
    username: root
    password: <PASSWORD>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
    open-in-view: true
  thymeleaf:
    cache: false
  main:
    allow-circular-references: true
  web:
    locale: vi_VN
    locale-resolver: accept_header
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
    encoding:
      charset: UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: <EMAIL>
    password: <PASSWORD>
  messages:
    basename: messages, validation
    encoding: UTF-8
paypal:
  mode: sandbox
  client.id: { PAYPAL_CLIENT_ID }
  client.secret: { PAYPAL_CLIENT_SECRET }